In [15]:
import pandas as pd
import numpy as np
from keras import Input,backend
from keras.models import Model
from keras.layers import *
from keras.callbacks import Callback
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score, accuracy_score, matthews_corrcoef

In [16]:
dataset = pd.read_csv("../datasets/train_test_data.csv",
                           header=0, parse_dates=[0], index_col=0)
label_strt_index = -1
data, labels  = dataset.iloc[:,:label_strt_index], dataset.iloc[:,label_strt_index:]

In [23]:
dataset[dataset["Past 20-day events"] > 0]

^SSEC   ^GDAXHI      ^PSI      ^HSI     ^TWII     ^GSPC  \
1997-02-27  0.470925  0.447339  0.410245  0.422330  0.595548  0.374391   
1997-02-28  0.575238  0.396141  0.407266  0.387672  0.538787  0.412342   
1997-03-01  0.612154  0.408283  0.432117  0.446161  0.600191  0.465813   
1997-03-03  0.612154  0.408283  0.432117  0.446161  0.401271  0.465813   
1997-03-04  0.525695  0.531801  0.408308  0.408220  0.569612  0.411679   
1997-03-05  0.425558  0.447163  0.415655  0.412257  0.556535  0.505979   
1997-03-06  0.631096  0.435908  0.413549  0.422524  0.554819  0.417525   
1997-03-07  0.494769  0.441620  0.433766  0.403136  0.572953  0.477209   
1997-03-08  0.604456  0.424088  0.429793  0.405426  0.515678  0.490579   
1997-03-10  0.604456  0.424088  0.429793  0.405426  0.490120  0.490579   
1997-03-11  0.547609  0.416697  0.417905  0.417394  0.563690  0.424500   
1997-03-12  0.576274  0.345299  0.415762  0.390360  0.505258  0.395942   
1997-03-13  0.461491  0.383550  0.416738  0.373899  0.509447  0.349610   
1997-03-14  0.539954  0.459930  0.398524  0.378252  0.504328  0.460450   
1997-03-15  0.648222  0.315769  0.423584  0.445864  0.511812  0.453806   
1997-03-17  0.648222  0.315769  0.423584  0.445864  0.619058  0.453806   
1997-03-18  0.519500  0.336378  0.409277  0.399783  0.585871  0.401389   
1997-03-19  0.495462  0.427637  0.410477  0.397726  0.423639  0.414376   
1997-03-20  0.324738  0.330770  0.433320  0.377714  0.542789  0.419011   
1997-03-21  0.711042  0.467785  0.421289  0.425431  0.267251  0.447258   
1997-03-22  0.607824  0.424857  0.449343  0.485199  0.501262  0.480278   
1997-03-24  0.607824  0.424857  0.449343  0.485199  0.237763  0.480278   
1997-03-25  0.527314  0.503400  0.406938  0.441354  0.400647  0.427109   
1997-03-26  0.575157  0.488889  0.447382  0.407799  0.674240  0.447063   
1997-03-27  0.497008  0.368711  0.426562  0.362979  0.553672  0.336285   
1997-03-28  0.453095  0.238196  0.426562  0.308379  0.525263  0.333217   
1997-03-31  0.635766  0.238196  0.426562  0.308379  0.391653  0.333217   
1997-04-01  0.527643  0.238196  0.371489  0.308379  0.645847  0.454417   
1997-04-02  0.472112  0.313155  0.416229  0.437054  0.534588  0.377416   
1997-04-03  0.551316  0.405673  0.363552  0.400694  0.646300  0.439630   
...              ...       ...       ...       ...       ...       ...   
2018-03-02  0.471680  0.286608  0.423777  0.375602  0.437112  0.462873   
2018-03-05  0.505109  0.484672  0.396962  0.351163  0.459147  0.491786   
2018-03-06  0.552184  0.422073  0.415971  0.485471  0.596661  0.451072   
2018-03-07  0.473746  0.454429  0.445237  0.389617  0.470682  0.435924   
2018-03-08  0.527262  0.457075  0.417282  0.467833  0.551672  0.459921   
2018-03-09  0.530238  0.410917  0.422859  0.455512  0.526266  0.522574   
2018-03-12  0.531252  0.427658  0.460382  0.480570  0.591786  0.432092   
2018-03-13  0.476350  0.333631  0.412774  0.421933  0.560983  0.407403   
2018-03-14  0.472557  0.403724  0.397473  0.405047  0.459478  0.410503   
2018-03-15  0.500964  0.449230  0.360602  0.431617  0.483905  0.434479   
2018-10-12  0.547296  0.409946  0.487562  0.486359  0.679772  0.507184   
2018-10-15  0.426069  0.428548  0.387873  0.378766  0.390324  0.409627   
2018-10-16  0.458496  0.498403  0.457121  0.423319  0.557829  0.542543   
2018-10-17  0.531735  0.383597  0.482820  0.420309  0.496178  0.437046   
2018-10-18  0.352895  0.356885  0.447101  0.420309  0.478668  0.368459   
2018-10-19  0.631689  0.383500  0.431737  0.434147  0.471838  0.436520   
2018-10-22  0.708467  0.388966  0.467902  0.492419  0.538970  0.417416   
2018-10-23  0.386959  0.289294  0.408209  0.326414  0.348924  0.411535   
2018-10-24  0.517891  0.372357  0.393776  0.409502  0.485598  0.288553   
2018-10-25  0.502350  0.468903  0.347414  0.390150  0.315470  0.528619   
2018-10-26  0.491762  0.358198  0.475409  0.387187  0.472903  0.354220   
2018-10-29  0.390916  0.463856  0.448744  0.432984  0.518952  0.406452   
2018-10-30  0.55301

In [6]:
def print_metric(y_true, y_pred):
    print('F1 score: %f' % f1_score(y_true, y_pred))
    print('precision score: %f' % precision_score(y_true, y_pred))
    print('recall score: %f' % recall_score(y_true, y_pred))
    print('accuracy score: %f' % accuracy_score(y_true, y_pred))
    print('matthews_corrcoef: %f' % matthews_corrcoef(y_true, y_pred))
    print('\nConfusion matrix:')
    print(confusion_matrix(y_true, y_pred, labels=[0,1]))

In [7]:
def train_dev_test_split(dataset, train_ratio, dev_ratio, test_ratio):
    size_of_data = dataset.shape[0]
    train_data, temp = dataset[:int(size_of_data* train_ratio)], dataset[int(size_of_data* train_ratio):] 
 
    #split for dev and test sets
    dev_split_ratio = dev_ratio/(dev_ratio+test_ratio)
    dev_data, test_data = temp[:int(len(temp)*dev_split_ratio)], temp[int(len(temp)*dev_split_ratio):]
    
    return train_data, dev_data, test_data

In [8]:
def predict_classes(model, X):
    """
    Input
        model: keras model
        X: input data

    Output
        2D numpy array of shape (X.shape[0], 1)
    """
    y_pred = model.predict(X)
    
    #convert probs to binary classes
    y_pred = np.where(y_pred > 0.5, 1, 0)
    
    return y_pred

In [9]:
def print_unique_counts(x):
    unique, counts = np.unique(x, return_counts=True)
    print(np.asarray((unique, counts)).T)


In [10]:
#Split data
DEV_RATIO, TEST_RATIO = 0.15, 0.15
TRAIN_RATIO = 1-DEV_RATIO-TEST_RATIO

train_data, dev_data, test_data = train_dev_test_split(data, TRAIN_RATIO, DEV_RATIO, TEST_RATIO)
train_label, dev_label, test_label = train_dev_test_split(labels, TRAIN_RATIO, DEV_RATIO, TEST_RATIO)

In [11]:
input_dim = train_data.shape[1]


#Build layers
econ_indicator_input = Input(shape=(input_dim,))
x = Dense(32,activation='relu')(econ_indicator_input)
x = Dense(16,activation='relu')(x)

#output activations
crisis_in_next_N_days = [Dense(1, activation='sigmoid')(x)]

#compile the model
model = Model(econ_indicator_input, crisis_in_next_N_days)
model.compile(optimizer='adam', loss='binary_crossentropy')


print(model.summary())
#fit the model

model.fit(train_data, train_label, epochs=10, batch_size=64, verbose=1)


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 169)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                5440      
_________________________________________________________________
dense_2 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17        
Total params: 5,985
Trainable params: 5,985
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
3954/3954 [==============================] - 1s 182us/step - loss: 0.5641
Epoch 2/10
3954/3954 [==============================] - 0s 106us/step - loss: 0.5532
Epoch 3/10
3954/3954 [==============================] - 0s 109us/step - loss: 0.5455
Epoch 4/10
3

In [12]:
#Make predictions for train set
y_pred = predict_classes(model,train_data)
print_metric(train_label, y_pred)

F1 score: 0.194660
precision score: 0.638418
recall score: 0.114837
accuracy score: 0.763531
matthews_corrcoef: 0.195049

Confusion matrix:
[[2906   64]
 [ 871  113]]


In [13]:
#Make predictions from dev set
y_pred = predict_classes(model,dev_data)
print_metric(dev_label, y_pred)


F1 score: 0.000000
precision score: 0.000000
recall score: 0.000000
accuracy score: 0.981132
matthews_corrcoef: -0.008829

Confusion matrix:
[[832   5]
 [ 11   0]]


In [14]:
#Make predictions for test set
y_pred = predict_classes(model,test_data)
print_metric(test_label, y_pred)

F1 score: 0.000000
precision score: 0.000000
recall score: 0.000000
accuracy score: 0.964623
matthews_corrcoef: 0.000000

Confusion matrix:
[[818   0]
 [ 30   0]]


/home/kevin/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/kevin/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/kevin/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/metrics/classification.py:872: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
